# Server Configuration
server.port=8080
server.servlet.context-path=/

# Application Name
spring.application.name=secure-banking-app

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/secure_banking_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123

# Email Configuration (Gmail App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Import fichier sécurisé
spring.config.import=optional:application-secret.properties

# Session Configuration
server.servlet.session.timeout=15m
server.servlet.session.cookie.name=SECURE_BANKING_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict

# Account Lock Configuration
secure.banking.max-failed-attempts=5
secure.banking.lockout-duration-minutes=30

# Logging Configuration
logging.level.com.securebank=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


# SSL HTTPS configuration
server.ssl.enabled=true
server.ssl.key-store=file:C:/Users/Dell/secure-banking-app/backend/src/main/resources/securebank.p12
server.ssl.key-store-password=securebank
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=securebank
# Force HTTPS
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2
server.ssl.ciphers=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256