# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/secure_banking_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Email Configuration (SMTP)
spring.config.import=optional:classpath:application-secret.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Session Configuration
server.servlet.session.timeout=15m
server.servlet.session.cookie.name=SECURE_BANKING_SESSION
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123

# Application Configuration
app.name=Secure Banking Application
app.version=1.0.0

# Encryption Configuration
app.encryption.key=SecureBankingKey2024TunisiaAES256

# OTP Configuration
app.otp.expiry-minutes=5
app.otp.max-attempts=3
app.otp.block-duration-minutes=15

#TLS/SSL Configuration
server.port=8080
server.ssl.enabled=true
server.ssl.key-store=classpath:localhost.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=1

# Account Lock Configuration
app.security.max-login-attempts=5
app.security.lock-duration-minutes=30

# Logging Configuration
logging.level.com.securebank=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n